CREATE TABLE settings (
    id INTEGER PRIMARY KEY,
    edge_protocol VARCHAR(30),
    cloud_protocol VARCHAR(30),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);