#!/bin/bash
set -e

rm -f /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/iiotdashboard /etc/nginx/sites-enabled/iiotdashboard

if nginx -t; then

    systemctl reload nginx

    if [ $? -eq 0 ]; then
        systemctl start nginx
    fi

else
    echo "NGINX config test failed. Not reloading." >&2
    exit 1
fi

exit 0